r"""跨资产自动pregrasp/contact-basin schema、cache与fail-closed provider。"""

from .cache import (
    AtomicPregraspCache,
    PregraspCacheError,
    PregraspConflictError,
    PregraspIndex,
    PregraspIndexEntry,
    PregraspIndexError,
)
from .provider import (
    FilePregraspProvider,
    PregraspCorruptError,
    PregraspInsufficientTierError,
    PregraspMissError,
    PregraspPointOnlyError,
    PregraspProviderError,
    PregraspQuery,
    PregraspResolution,
)
from .schema import (
    PREGRASP_INDEX_ARTIFACT_TYPE,
    PREGRASP_RECORD_ARTIFACT_TYPE,
    PREGRASP_SCHEMA_VERSION,
    SCALE_ANCHORS,
    PregraspCandidate,
    PregraspCoverage,
    PregraspGate,
    PregraspLookupKey,
    PregraspMetrics,
    PregraspRecord,
    PregraspTier,
    ScaleCertificate,
    ScaleStressSample,
    active_mask_digest,
    certify_pregrasp,
    tier_satisfies,
)

__all__ = [
    "PREGRASP_INDEX_ARTIFACT_TYPE",
    "PREGRASP_RECORD_ARTIFACT_TYPE",
    "PREGRASP_SCHEMA_VERSION",
    "SCALE_ANCHORS",
    "AtomicPregraspCache",
    "FilePregraspProvider",
    "PregraspCacheError",
    "PregraspCandidate",
    "PregraspConflictError",
    "PregraspCorruptError",
    "PregraspCoverage",
    "PregraspGate",
    "PregraspIndex",
    "PregraspIndexEntry",
    "PregraspIndexError",
    "PregraspInsufficientTierError",
    "PregraspLookupKey",
    "PregraspMetrics",
    "PregraspMissError",
    "PregraspPointOnlyError",
    "PregraspProviderError",
    "PregraspQuery",
    "PregraspRecord",
    "PregraspResolution",
    "PregraspTier",
    "ScaleCertificate",
    "ScaleStressSample",
    "active_mask_digest",
    "certify_pregrasp",
    "tier_satisfies",
]
