r"""MDP terms for generalized manipulation tasks.

这里是 `gm` 环境自己的 MDP 语义层。设计原则：

- 能直接复用 Isaac Lab 通用项时，不复制实现；
- 一旦涉及 AnyMani 的 hand asset metadata、same-topology contract、
  object-in-hand 成功判据、morphology-aware observation，就在 `gm/mdp`
  下显式落名；
- 不从旧 `tasks/inhand` 继续借模块名，避免把 LEAP-specific 历史语义带入新主线。
"""

from __future__ import annotations

from .actions import (
    ClampedRelativeJointActionCfg,
    ClampedRelativeJointPositionAction,
    PolicyStepADRTargetJointPositionAction,
    PolicyStepADRTargetJointPositionActionCfg,
)
from .adr_ranges import (
    GM_ADR_HAND_MATERIAL_FINAL,
    GM_ADR_HAND_MATERIAL_INITIAL,
    GM_ADR_OBJECT_BODY_YAW_FINAL,
    GM_ADR_OBJECT_MATERIAL_FINAL,
    GM_ADR_OBJECT_MATERIAL_INITIAL,
)
from .commands.commands_cfg import ReorientCommandCfg, TactileRotationCommandCfg
from .commands.reorient_command import ReorientCommand
from .commands.tactile_rotation_command import TactileRotationCommand, ensure_post_physics_progress_updated
from .curriculums import LeapADRByNetRotationRate, RewardCurriculumByGoalSuccess, RewardCurriculumByNetRotation
from .events import (
    RandomizeActuatorGainsAndRecord,
    RandomizeRigidBodyMassAndRecord,
    RandomizeRigidBodyMaterialAndRecord,
    apply_adr_object_wrench,
    apply_generated_structural_collision_filter,
    compose_body_yaw_reset_quaternion,
    generated_structural_collision_filter_pairs,
    randomize_object_com_from_default_and_record,
    randomize_object_scale_and_record,
    record_object_reset_anchor,
    record_robot_reset_joint_anchor,
    resample_adr_material_buckets,
    reset_adr_episode_length,
    reset_adr_object_state,
    reset_adr_robot_joints,
    reset_adr_wrench_state,
    reset_tactile_contact_state,
)
from .observations import (
    adr_actual_state,
    finger_non_tip_contact_bits_ema,
    fingertip_contact_binary,
    fingertip_contact_force,
    joint_pos_limit_normalized,
    joint_pos_raw,
    joint_soft_pos_limits,
    joint_target,
    joint_vel_raw,
    last_action,
    last_processed_action,
    object_goal_task_state,
    object_orientation,
    object_pos,
    palm_force_magnitude_ema,
    reorient_command,
    reward_release_coefficient,
    tip_contact_bits_ema,
    tip_force_magnitude_ema,
)
from .rewards import (
    AxisDeltaRotationReward,
    action_l2_curriculum,
    action_rate_l2_curriculum,
    bad_non_tip_contact,
    failure_termination_impulse,
    goal_success_bonus,
    good_fingertip_contact,
    joint_mechanical_power_curriculum,
    joint_pose_anchor_l2_curriculum,
    keypoint_reorientation_reward,
    object_axis_speed_band_curriculum,
    object_axis_speed_jitter_curriculum,
    object_lin_vel_l2_curriculum,
    object_off_axis_ang_vel_curriculum,
    reorientation_reward_placeholder,
    tactile_axis_delta_rotation_rate,
    tactile_bad_finger_non_tip_contact,
    tactile_full_pose_keypoint_reward,
    tactile_goal_success_impulse,
    tactile_good_tip_contact,
    termination_penalty_placeholder,
    torque_l2_curriculum,
)
from .tactile_diagnostics_state import GmTactileEpisodeDiagnostics
from .terminations import (
    adr_randomized_time_out,
    object_falling_placeholder,
    object_out_of_hand,
    tactile_goal_axis_misaligned,
    tactile_object_out_of_anchor,
)

__all__ = [
    "AxisDeltaRotationReward",
    "ClampedRelativeJointActionCfg",
    "ClampedRelativeJointPositionAction",
    "GM_ADR_HAND_MATERIAL_FINAL",
    "GM_ADR_HAND_MATERIAL_INITIAL",
    "GM_ADR_OBJECT_BODY_YAW_FINAL",
    "GM_ADR_OBJECT_MATERIAL_FINAL",
    "GM_ADR_OBJECT_MATERIAL_INITIAL",
    "GmTactileEpisodeDiagnostics",
    "PolicyStepADRTargetJointPositionAction",
    "PolicyStepADRTargetJointPositionActionCfg",
    "LeapADRByNetRotationRate",
    "RandomizeActuatorGainsAndRecord",
    "RandomizeRigidBodyMassAndRecord",
    "RandomizeRigidBodyMaterialAndRecord",
    "ReorientCommand",
    "ReorientCommandCfg",
    "RewardCurriculumByGoalSuccess",
    "RewardCurriculumByNetRotation",
    "TactileRotationCommand",
    "TactileRotationCommandCfg",
    "action_l2_curriculum",
    "action_rate_l2_curriculum",
    "adr_actual_state",
    "adr_randomized_time_out",
    "apply_adr_object_wrench",
    "apply_generated_structural_collision_filter",
    "compose_body_yaw_reset_quaternion",
    "bad_non_tip_contact",
    "finger_non_tip_contact_bits_ema",
    "fingertip_contact_binary",
    "fingertip_contact_force",
    "ensure_post_physics_progress_updated",
    "failure_termination_impulse",
    "joint_pos_limit_normalized",
    "generated_structural_collision_filter_pairs",
    "goal_success_bonus",
    "good_fingertip_contact",
    "last_action",
    "joint_pos_raw",
    "joint_soft_pos_limits",
    "joint_target",
    "joint_vel_raw",
    "joint_mechanical_power_curriculum",
    "joint_pose_anchor_l2_curriculum",
    "keypoint_reorientation_reward",
    "last_processed_action",
    "object_goal_task_state",
    "object_orientation",
    "object_pos",
    "object_falling_placeholder",
    "object_out_of_hand",
    "object_axis_speed_band_curriculum",
    "object_axis_speed_jitter_curriculum",
    "object_lin_vel_l2_curriculum",
    "object_off_axis_ang_vel_curriculum",
    "palm_force_magnitude_ema",
    "record_object_reset_anchor",
    "record_robot_reset_joint_anchor",
    "randomize_object_com_from_default_and_record",
    "randomize_object_scale_and_record",
    "resample_adr_material_buckets",
    "reset_adr_episode_length",
    "reset_adr_object_state",
    "reset_adr_robot_joints",
    "reset_adr_wrench_state",
    "reset_tactile_contact_state",
    "reorient_command",
    "reward_release_coefficient",
    "reorientation_reward_placeholder",
    "termination_penalty_placeholder",
    "torque_l2_curriculum",
    "tactile_axis_delta_rotation_rate",
    "tactile_bad_finger_non_tip_contact",
    "tactile_full_pose_keypoint_reward",
    "tactile_goal_axis_misaligned",
    "tactile_goal_success_impulse",
    "tactile_good_tip_contact",
    "tactile_object_out_of_anchor",
    "tip_contact_bits_ema",
    "tip_force_magnitude_ema",
]
