r"""用4-env ManagerBased scene验证hetero pregrasp event/action partial-reset生命周期。

本脚本暂借旧GM scene作为Isaac harness，但被测``tasks/hetero``源码不import GM/inhand。它覆盖full reset、一次
policy update、六次physics apply、乱序partial reset与bad-identity fail-closed；输出只证明reset/action runtime
合同，不代表完整新任务、reward或PPO已经可用。
"""

from __future__ import annotations

import argparse
import json
import os
import traceback
from dataclasses import replace
from pathlib import Path
from typing import Any, cast

os.environ["ANYMANI_HETEROGENEOUS_ASSET_ROWS"] = "16"  # 单个已认证physical asset prototype

from isaaclab.app import AppLauncher  # noqa: E402  # environment routing必须在task import前固定

app_launcher = AppLauncher(headless=True)
simulation_app = app_launcher.app


def _parse_args() -> argparse.Namespace:
    r"""解析durable smoke evidence输出路径。"""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/pregrasp/schema_v2/runtime-smokes/hetero-pregrasp-partial-reset.json"),
    )
    return parser.parse_args()


def _clone_rows(tensors: dict[str, Any], rows: list[int]) -> dict[str, Any]:
    r"""复制non-reset tensor rows，供partial/fail-closed逐位对照。"""

    return {name: tensor[rows].clone() for name, tensor in tensors.items()}


def main() -> int:
    r"""运行真实ManagerBased reset/action smoke并输出关键误差。"""

    import anymani.tasks.gm  # noqa: F401  # 仅注册临时scene harness，不被tasks/hetero源码消费
    import gymnasium as gym
    import isaaclab.sim as sim_utils
    import torch
    from anymani.pregrasp import AtomicPregraspCache, PregraspMissError, PregraspRecord, active_mask_digest
    from anymani.pregrasp.isaac_runtime import hand_semantic_pose_w, object_pose_w_from_hand
    from anymani.tasks.gm.config.heterogeneous_asset.asset_runtime import (
        HETEROGENEOUS_ACTIVE_MASK_ROWS,
        HETEROGENEOUS_CANONICAL_ARTIFACTS,
        HETEROGENEOUS_HAND_SPAWN_CFG,
    )
    from anymani.tasks.gm.config.heterogeneous_asset.tactile_rotation_env_cfg import (
        HeterogeneousEventsCfg,
        HeterogeneousTactileRotationEnvCfg,
    )
    from anymani.tasks.hetero.mdp.actions import (
        POLICY_STEP_AUTHORITY_RAD,
        PreloadAwareMaskedRelativeJointPositionAction,
        PreloadAwareMaskedRelativeJointPositionActionCfg,
    )
    from anymani.tasks.hetero.mdp.events import (
        PregraspAssetBinding,
        PregraspResetCfg,
        reset_from_pregrasp_cache,
    )
    from anymani.tasks.hetero.mdp.runtime_state import (
        HETERO_PREGRASP_STATE_ATTR,
        HeterogeneousPregraspState,
        PregraspRuntimeIdentity,
    )
    from isaaclab.assets import Articulation, RigidObject
    from isaaclab.envs import ManagerBasedRLEnv
    from isaaclab.managers import EventTermCfg as EventTerm
    from isaaclab.utils import configclass

    args = _parse_args()  # smoke identity只接受durable output路径
    cache_root = Path("outputs/pregrasp/schema_v2/cache").resolve()  # production cache generated by P0001
    cache = AtomicPregraspCache(cache_root)
    cache_index = cache.load_index()
    scale_entry = next(
        entry for entry in cache_index.entries if entry.anchor == "1.2" and entry.tier.value == "contact_basin"
    )
    record = PregraspRecord.from_dict(json.loads(cache.payload_path(scale_entry).read_text()))
    frame = HETEROGENEOUS_HAND_SPAWN_CFG.frame  # generated-hand$T_{ha}$ calibration
    artifact = HETEROGENEOUS_CANONICAL_ARTIFACTS[0]  # env routing已固定为formal row16
    runtime_identity = PregraspRuntimeIdentity(
        source_content_hash=artifact.source_content_hash,
        physical_geometry_hash=artifact.physical_geometry_hash,
        canonical_schema_digest=artifact.schema_digest,
        routing_digest=active_mask_digest(HETEROGENEOUS_ACTIVE_MASK_ROWS[0]),
    )
    support_entry = next(
        entry for entry in cache_index.entries if entry.anchor == "1.2" and entry.tier.value == "support_basin"
    )
    support_record = PregraspRecord.from_dict(json.loads(cache.payload_path(support_entry).read_text()))
    try:
        PregraspAssetBinding.from_lookup_key(
            support_record.lookup_key,
            requested_scale=1.2,
            runtime_identity=runtime_identity,
        )
    except ValueError:
        runtime_identity_mismatch_rejected = True  # row0合法cache key不能绑定row16 physical scene
    else:
        raise AssertionError("runtime asset identity accepted another physical asset's cache key")
    reset_cfg = PregraspResetCfg(
        cache_root=str(cache_root),
        bindings=(
            PregraspAssetBinding.from_lookup_key(
                record.lookup_key,
                requested_scale=1.2,
                runtime_identity=runtime_identity,
            ),
        ),
        asset_index_by_env=(0, 0, 0, 0),
        semantic_R_ha=tuple(frame.semantic_R_ha),
        semantic_p_ha=(
            float(frame.semantic_p_ha[0]),
            float(frame.semantic_p_ha[1]),
            float(frame.semantic_p_ha[2]),
        ),
        minimum_tier=record.tier,
        require_basin=True,
    )

    @configclass
    class SmokeActionsCfg:
        r"""只替换旧harness action term，固定16-slot$1/24$ rad baseline。"""

        hand_joint_pos = PreloadAwareMaskedRelativeJointPositionActionCfg(
            asset_name="robot",
            joint_names=[".*"],
            preserve_order=True,
            scale=POLICY_STEP_AUTHORITY_RAD,
            use_zero_offset=True,
        )

    @configclass
    class SmokeEventsCfg(HeterogeneousEventsCfg):
        r"""保留scene startup原件，以新pregrasp event作为robot/object唯一reset writer。"""

        reset_robot_joints = None
        reset_object = None
        apply_object_offset = None
        record_object_anchor = None
        reset_from_cache = EventTerm(
            func=reset_from_pregrasp_cache,
            mode="reset",
            params={"config": reset_cfg},
        )

    env = None
    try:
        cfg = HeterogeneousTactileRotationEnvCfg()
        cfg.scene.num_envs = 4  # 两个reset、两个non-reset rows足以证伪stale污染
        cfg.scene.replicate_physics = False
        cfg.actions = SmokeActionsCfg()  # type: ignore[assignment]  # harness有意替换旧action config类型
        cfg.events = SmokeEventsCfg()
        object_spawn = cast(sim_utils.UsdFileCfg, cfg.scene.object.spawn)
        object_spawn.scale = (1.2, 1.2, 1.2)  # 与cache退化interval$[1.2,1.2]$ exact匹配
        env = gym.make("AnyMani-GM-HeterogeneousAsset-TactileRotation-v0", cfg=cfg)
        runtime_env = cast(ManagerBasedRLEnv, env.unwrapped)
        runtime_env.sim._app_control_on_stop_handle = None
        env.reset()  # 真顺序：event reset -> action manager reset

        robot = cast(Articulation, runtime_env.scene["robot"])
        object_asset = cast(RigidObject, runtime_env.scene["object"])
        action = cast(
            PreloadAwareMaskedRelativeJointPositionAction,
            runtime_env.action_manager.get_term("hand_joint_pos"),
        )
        sidecar = getattr(runtime_env, HETERO_PREGRASP_STATE_ATTR)
        if not isinstance(sidecar, HeterogeneousPregraspState) or not bool(sidecar.valid.all().item()):
            raise AssertionError("full reset did not publish a valid pregrasp sidecar")

        # Full reset必须保持actual/controller target分离，并写入hand-frame组合后的world object pose。
        active = sidecar.active_joint_mask
        preload_delta = (sidecar.q_target_rad - sidecar.q_state_rad)[active]
        if not bool((preload_delta.abs() > 1.0e-6).any().item()):
            raise AssertionError("pregrasp reset lost all PD preload")
        if not torch.allclose(robot.data.joint_pos_target, sidecar.q_target_rad, atol=1.0e-6, rtol=0.0):
            raise AssertionError("articulation target disagrees with pregrasp sidecar")
        if not torch.equal(action.current_targets, sidecar.q_target_rad):
            raise AssertionError("action reset did not restore sidecar q_target")
        hand_pos_w, hand_quat_w = hand_semantic_pose_w(
            robot.data.root_pos_w,
            robot.data.root_quat_w,
            frame.semantic_R_ha,
            frame.semantic_p_ha,
        )
        expected_object_pos_w, expected_object_quat_w = object_pose_w_from_hand(
            hand_pos_w,
            hand_quat_w,
            sidecar.object_position_h_m,
            sidecar.object_quat_h_wxyz,
        )
        if not torch.allclose(object_asset.data.root_pos_w, expected_object_pos_w, atol=1.0e-6, rtol=0.0):
            raise AssertionError("object world position disagrees with T_wh T_ho")
        orientation_dot = torch.abs((object_asset.data.root_quat_w * expected_object_quat_w).sum(dim=-1))
        if not torch.allclose(orientation_dot, torch.ones_like(orientation_dot), atol=1.0e-6, rtol=0.0):
            raise AssertionError("object world orientation disagrees with T_wh T_ho")

        # 一个policy sample只推进一次；六次apply只重复写相同setpoint。
        initial_target = action.current_targets.clone()
        policy_action = torch.ones_like(action.raw_actions)
        runtime_env.action_manager.process_action(policy_action)
        expected_delta = torch.full_like(initial_target, POLICY_STEP_AUTHORITY_RAD)
        expected_target = torch.clamp(
            initial_target + expected_delta,
            min=robot.data.soft_joint_pos_limits[..., 0],
            max=robot.data.soft_joint_pos_limits[..., 1],
        )
        expected_target = torch.where(active, expected_target, torch.zeros_like(expected_target))
        if not torch.allclose(action.current_targets, expected_target, atol=1.0e-7, rtol=0.0):
            raise AssertionError("one policy sample did not produce exactly one 1/24-rad target update")
        for _ in range(6):
            runtime_env.action_manager.apply_action()
        if not torch.equal(action.current_targets, expected_target):
            raise AssertionError("physics apply repeated the policy target accumulation")

        # Partial reset[3,1]必须恢复preload/清action，而non-reset[0,2]逐位保持。
        reset_ids = torch.tensor((3, 1), device=runtime_env.device)
        kept_ids = [0, 2]
        tracked = {
            "current": action.current_targets,
            "previous": action.previous_targets,
            "raw": action.raw_actions,
            "processed": action.processed_actions,
            "executed": action.executed_actions,
            "joint_target": robot.data.joint_pos_target,
            "object_pose": object_asset.data.root_state_w[:, :7],
            "object_velocity": object_asset.data.root_state_w[:, 7:13],
        }
        kept_before = _clone_rows(tracked, kept_ids)
        runtime_env._reset_idx(reset_ids.tolist())  # 调用真实event->manager lifecycle；输入API接受Sequence
        for name, tensor in tracked.items():
            if not torch.equal(tensor[kept_ids], kept_before[name]):
                raise AssertionError(f"partial reset changed non-reset rows in {name}")
        if not torch.equal(action.current_targets[reset_ids], sidecar.q_target_rad[reset_ids]):
            raise AssertionError("partial action reset did not restore selected preload targets")
        for buffer in (action.raw_actions, action.processed_actions, action.executed_actions):
            if not torch.equal(buffer[reset_ids], torch.zeros_like(buffer[reset_ids])):
                raise AssertionError("partial reset retained stale selected action rows")

        # Wrong physical identity必须在provider阶段抛错，且robot/object/sidecar selected row保持原值。
        bad_key = replace(record.lookup_key, search_identity={"algorithm": "intentionally-missing-smoke-key"})
        bad_cfg = replace(
            reset_cfg,
            bindings=(
                PregraspAssetBinding.from_lookup_key(
                    bad_key,
                    requested_scale=1.2,
                    runtime_identity=runtime_identity,
                ),
            ),
        )
        fail_ids = torch.tensor((1,), device=runtime_env.device)
        fail_tracked = {
            "q": robot.data.joint_pos,
            "target": robot.data.joint_pos_target,
            "object": object_asset.data.root_state_w,
            "sidecar_q": sidecar.q_state_rad,
            "sidecar_target": sidecar.q_target_rad,
        }
        failed_before = _clone_rows(fail_tracked, [1])
        try:
            reset_from_pregrasp_cache(runtime_env, fail_ids, config=bad_cfg)
        except PregraspMissError:
            pass
        else:
            raise AssertionError("bad physical identity unexpectedly resolved a pregrasp")
        for name, tensor in fail_tracked.items():
            if not torch.equal(tensor[[1]], failed_before[name]):
                raise AssertionError(f"provider miss mutated {name} before failing")

        # 一次真实physics step应让q_t-q_s产生finite nonzero implicit-PD effort。
        runtime_env.scene.write_data_to_sim()
        runtime_env.sim.step(render=False)
        runtime_env.scene.update(runtime_env.physics_dt)
        selected_effort = robot.data.computed_torque[reset_ids][active[reset_ids]]
        if not bool(torch.isfinite(selected_effort).all().item()) or not bool(
            (selected_effort.abs() > 1.0e-8).any().item()
        ):
            raise AssertionError("PD preload did not produce finite nonzero actuator effort")

        evidence = {
            "artifact_type": "anymani.hetero.pregrasp_partial_reset_smoke",
            "schema_version": "1.0.0",
            "num_envs": runtime_env.num_envs,
            "partial_reset_ids": reset_ids.tolist(),
            "kept_ids": kept_ids,
            "cache_index_digest": cache_index.digest,
            "record_digest": record.digest,
            "lookup_digest": record.lookup_key.digest,
            "preload_max_abs_rad": float(preload_delta.abs().max().item()),
            "policy_step_authority_rad": POLICY_STEP_AUTHORITY_RAD,
            "nonzero_effort_max_N_m": float(selected_effort.abs().max().item()),
            "provider_miss_zero_side_effect": True,
            "runtime_identity_mismatch_rejected": runtime_identity_mismatch_rejected,
            "partial_reset_nonselected_rows_unchanged": True,
            "six_substeps_target_idempotent": True,
            "object_hand_world_frame_roundtrip_passed": True,
        }
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print(json.dumps({"output": str(args.output), **evidence}, sort_keys=True))
        return 0
    finally:
        if env is not None:
            env.close()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception:
        traceback.print_exc()
        raise
    finally:
        simulation_app.close()
